name: Build Windows Executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          main.py
          requirements.txt
          levels/
          doom_icon.ico
        sparse-checkout-cone-mode: false
        fetch-depth: 1
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        pip install pygame numpy pillow pyinstaller
    
    - name: Build portable exe
      run: |
        pyinstaller main.py --onefile --name DOOMDarkAges --windowed --icon=doom_icon.ico --add-data "levels;levels"
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DOOMDarkAges-Windows-Portable
        path: dist/DOOMDarkAges.exe